#!/usr/bin/env bash

STYLESHEET="bastilian.xsl"
OPEN="<?xml version=\"1.0\" encoding=\"UTF-8\"?><?xml-stylesheet href=\"$STYLESHEET\" type=\"text/xsl\"?><contents><![CDATA["
CLOSE="]]></contents>"

for f in $(find site -name '*.md'); do
  filename=${f%.*}
  pandoc -f markdown_github -t html $f
  mkdir -p $(dirname output/$filename)
  echo $OPEN$(pandoc -f markdown_github -t html $f)$CLOSE > output/$filename
done
§
